title:            Xilai Li's site
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //xilaili.github.io
#http://localhost:5000
#https://xilaili.github.io
disqus_shortname: xilaili

# Owner/author information
owner:
  name:           Xilai Li (李曦来)
  avatar:         xilai.jpg
  bio:            I'm from Shenyang, China. Currently in Raleigh, North Carolina. Passionate about computer vision, deep learning and basketball.
  email:          xli47@ncsu.edu
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: xilai-li-10a293125
  google_scholar: 5Pjns7kAAAAJ
  github: xilaili
# Analytics and webmaster tools stuff goes here
google_analytics: UA-52736040-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Research
    url: /blog/
  - title: Publications
    url: /publications/
  - title: Code
    url: /code/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Detroit
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
